name: Upload Binaries to Github

on:
    workflow_dispatch: # manually trigger
    schedule:
        - cron: "0 0 * * 0" # every Sunday

jobs:
    upload-package:
        name: Upload to Github Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                repository: IGinX-THU/IGinX
                ref: main
                path: iginx
            - uses: actions/checkout@v4
              with:
                path: zeppelin-interpreter
            - uses: actions/setup-java@v4
              with:
                  java-version: "8"
                  distribution: "temurin"
                  cache: "maven"
            - name: Install IGinX
              id: iginx
              working-directory: iginx
              shell: bash
              run: |
                  mvn install --batch-mode -P !format -DskipTests=true
                  VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  DATE=$(date +%Y%m%d%H%M%S)
                  echo "date=$DATE" >> $GITHUB_OUTPUT
            - name: Package zeppelin-interpreter
              id: package
              working-directory: zeppelin-interpreter
              run: |
                  mvn package \
                    --batch-mode \
                    -DskipTests=true \
                    -D"iginx.version=${{ steps.iginx.outputs.version }}" \
                    -P get-jar-with-dependencies \
                    -P !format
                  VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  name: auto build ${{ steps.iginx.outputs.date }}
                  tag_name: v${{ steps.iginx.outputs.date }}
                  body: |
                      build date: ${{ steps.iginx.outputs.date }}
                      branch: ${{ github.ref }}
                      iginx version: ${{ steps.iginx.outputs.version }}
                      zeppelin-interpreter version: ${{ steps.package.outputs.version }}
                  files: zeppelin-interpreter/**.jar
                  fail_on_unmatched_files: true
            - if: ${{ failure() }}
              name: report failure to issue
              uses: dacbd/create-issue-action@main
              with:
                  title: Auto build failed for commit ${{github.sha}}
                  body: |
                      build date: ${{ steps.iginx.outputs.date }}
                      branch: ${{ github.ref }}
                      zeppelin-interpreter version: ${{ steps.package.outputs.version }}
                      iginx version: ${{ steps.iginx.outputs.version }}
                      Please check the logs of workflow ${{ github.run_id }} for more information.
